config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :memorized_lines
  resources :lyrics
  #resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  get '/users/login', to: 'users#loginform', as: 'user_login'
  post '/users/login', to: 'users#handle_login'
  post '/logout', to: 'users#logout'

  get "/users", to: 'users#index', as: "users" # index
  get '/users/new', to: 'users#new', as: 'new_user' #new
  post '/users', to: 'users#create' #create
  get "/users/:id", to: "users#show", as: "user" #show
  get "/users/:id/edit", to: 'users#edit', as: "edit_user" #edit
  patch "/users/:id", to: 'users#update' #update
  delete "/users/:id", to: 'users#destroy' #destroy

  
  patch '/cart', to:"carts#update" #cart session. not complete
  patch "/sessions/reset_views", to: "sessions#reset_views" #advertisement video. limiting user view

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lyric.rb
class Lyric < ApplicationRecord
    has_many :memorized_lines
    has_many :users, through: :memorized_lines
    belongs_to :song
end

app/models/memorized_line.rb
class MemorizedLine < ApplicationRecord
    belongs_to :user
    belongs_to :lyric
end

app/models/song.rb
class Song < ApplicationRecord
    has_many :lyrics
end

app/models/user.rb
class User < ApplicationRecord
    has_many :memorized_lines
    has_many :lyrics, through: :memorized_lines
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :logged_in_user, :logged_in?
    before_action :set_page_view

    # makes controller methods available in the erb view files
    # use the helper_methods in your show to limit what the user can see
  
    def logged_in_user
      # will return nil if nobody is logged in
      # will return the instance if someone is logged in
      # if session[:pet_id]
        @logged_in_user = User.find_by(id: session[:user_id])
 #       byebug
      # end
    end
  
    def logged_in?
      # Returning true or false, depending on if someone is logged in
      !!logged_in_user
    end
  
    # Stop the view/action from completely being rendered onto the page
    def check_to_see_if_someones_logged_in
      # if they are not logged in, they will be sent to the login page
      redirect_to user_login_path unless logged_in?
    end

    private

    def set_page_view
        unless session[:views_remaining]
            session[:views_remaining] = 3
        end
    end
end

app/controllers/carts_controller.rb
#not implemented correctly yet. Tues 12:05pm 

class CartsController < ApplicationController
    def update
        byebug

        flash[:notice] = "You've added the #{params[:lyrics_id]} to your music brain library"

        session[:cart] << params[:lyrics_id]

        redirect_to lyric_path
        
    end

end

app/controllers/lyrics_controller.rb
class LyricsController < ApplicationController
    before_action :check_to_see_if_someones_logged_in, only: [:show]
    def show
        @lyrics = Lyric.all
        @lyric = Lyric.find_by(song_id: params[:id])
    
        session[:views_remaining] = session[:views_remaining] -1
    end



end

app/controllers/memorized_lines_controller.rb
class MemorizedLinesController < ApplicationController
      before_action :check_to_see_if_someones_logged_in

      def index
        @memorized_lines = @logged_in_user.memorized_lines
      end
    
      def new
          @memorized_line = MemorizedLine.new
          @lyrics = Lyric.all
      end

      def create
        # byebug
        @memorized_line = @logged_in_user.memorized_lines.create(lyric_id: params[:memorized_line][:lyric_id], user_id:logged_in_user.id)
          
        redirect_to new_memorized_line_path
      
      end
      def show
        @memorized_line = MemorizedLine.find(params[:id])
      end

      def update

      end
    
      def edit
   
      end
    
      def destroy
        @memorized_line = MemorizedLine.find(params[:id])
        @user = @memorized_line.user
        @memorized_line.destory
        redirect_to users_path(@user)
    end

    private

    def appointment_params_helper_method
    params.require(:memorized_lines).permit(:lyric_id, :user_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def reset_views
        session[:views_remaining] = 3
        redirect_back(fallback_location: lyrics_path)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

    def index
        @songs = Song.all
    end

    def show 
        @song = Song.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
      def index
        @users = User.all
      end
    
      def show
        @user = User.find(params[:id])
      end
    
      def new
        @user = User.new
      end
      
      def create
        @user = User.create(check_params)
        if @user.valid?
          redirect_to users_path
        else
          flash[:errors] = @user.error.full_messages
          redirect_to new_user_path
        end
      end

  #######
      def loginform
        @errors = flash[:errors]
      end
    
      def handle_login
        @user = User.find_by(username: params[:username])
        #byebug
        if @user && @user.authenticate(params[:password])
          session[:user_id] = @user.id
          #byebug
          redirect_to @user
        else
          flash[:error] = "Invalid username or password"
          redirect_to user_login_path
        end
      end
    
    
      def logout
        session[:user_id] = nil
        redirect_to user_login_path
      end
  
#      byebug
      def edit
        @user = User.find(params[:id])
        #byebug
          unless logged_in_user.id == @user.id #have to call the method from application_controller 
          #byebug
          redirect_to @logged_in_user
        end
      end
    
      def update
        @user = User.find(params[:id])
        @user.update(check_params)
        redirect_to users_path
      end
    
      def destroy
        user = User.find(params[:id])
        user.destroy

        redirect_to users_path
      end

      private

      def check_params
        params.require(:user).permit(:username, :password)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lyrics_helper.rb
module LyricsHelper
end

app/helpers/memorized_lines_helper.rb
module MemorizedLinesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/structures_helper.rb
module StructuresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dreemlyrics</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>



  <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <a class="navbar-brand" href="/songs">Dreem Lyrics </a>


           <% if logged_in? %>
              Welcome, <%= logged_in_user.username %>!
              <%= button_to "Log out", "/logout" %>
            <% else %>
              <%= link_to "Log In", user_login_path %>
            <% end %>



          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

              <li class="nav-item active">
                <a class="nav-link" href="/songs">Songs</a>
              </li>

              <li class="nav-item">
                  <a class="nav-link" href="/users/new">For Our New Users</a>
              </li>
            </ul>
          </div>
        </nav>
    <%= yield %>
  </body>
</html>

app/views/lyrics/show.html.erb
<% if session[:views_remaining] > 0 %>
    <p> page views remaining: <%= session[:views_remaining] %> </p>

        <h1><%= @lyric.song.title %> by <%= @lyric.song.artist %></h1>
     
            <% @lyrics.each do |lyric| %>
                <h1><ul><%= link_to lyric.lines_of_lyrics, new_memorized_line_path %></ul></h1>
                <% end %>



        <button type="button"> I've memorized the whole song!</button>

        </div>

    <% else %>

    <iframe width="560" height="315" src="https://www.youtube.com/embed/sxKF19jYk68" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
    
    </iframe>
    <%= button_to "I watched the whole ad", "/sessions/reset_views", method: :patch, class:"button" %>

<% end %>

app/views/memorized_lines/index.erb
<h1> memorized index </h1>
    <% @memorized_line.each do |memorized| %>
            <%= memorized.lyrics %> 
    <% end %>

app/views/memorized_lines/new.erb
<h1>Memorized Lines</h1>

<%= form_for @memorized_line do |f|%>
    <%= f.label :lyric_id %>
    <%= f.collection_select :lyric_id, Lyric.all, :id, :lines_of_lyrics %>
    <%= f.submit%>
<%end%>

app/views/memorized_lines/show.erb
<h1>memorized show </h1>

app/views/songs/index.html.erb
<div class="container">
    <h1 class="display-3" style="padding-top: 30px;"><h1 style="text-align: center; color:#00ff00
; font-size:46px;">ALL OUR SONGS 🎶</h1>
<br/>
</div>

<div>
<%@songs.each do |song|%>
<div class="container">
    <h1 class="display-3" style="padding-top: 30px;"><h1 style="text-align: center; color:#00ff00
; font-size:46px;">
🎶
<%= song.artist%> | <%=link_to song.title, lyric_path(song.id)%></h1>

<%end%>

<br/>
</div>

app/views/users/_form.html.erb
<%= form_for @user, html: { class: "form" } do |f| %>
  
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.number_field :password %>
  

  <% if flash[:errors] %>
    <ul>
      <% flash[:errors].each do |error| %>
        <li class="error"><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.submit class: "button" %>
<% end %>

app/views/users/edit.erb
<h1> user edit page </h1>

<%= form_for @user do |f| %>
    <%= f.label :username  %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.text_field :password %>

    <%= f.submit "update" %>

<% end %>

app/views/users/edit.html.erb
<div class="container" style="padding-top: 30px;">
        <h1 class="display-3" style="padding-top: 30px;">Edit User's Form</h1>
        <br/>

    </div>
    
    <div class="container" style="padding-top: 30px;">

<%= form_for @user do |f| %>
    <%= f.label :username  %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.text_field :password %>

    <%= f.submit "update" %>

<% end %>

    <%= button_to "Delete", user_path(@user), method: :delete %>
    
</div>

app/views/users/index.html.erb
<h1 class="display-3" style="padding-top: 30px;">USER INDEX</h1>

<div class="container">
    <div class="row row-cols-2">

        <div class="col">
            <h2 style="padding: 15px;"> LYRICS~ </h2>
     

<%= button_to "Add New User", new_user_path, method: :get %>

<ul>  
<div class="col"> 
    <ul style= "list-style-type: none;">

    <% @users.each do |user| %>
         <li style="padding-top: 20px;">
    <li><%= link_to user.username, user_path(user) %></li> 
    <br>
    <% end %> 
            </ul>
        </div>

    </div>
</div>

<div class="container" style="padding-top: 30px;">
    <h3>New to memorizing lyrics? Add yourself to the family <%= link_to "here.", "/users/new" %></h3>
</div>

app/views/users/login.html.erb
<h1>Login Form!</h1>

<%= form_tag "/users/login", method: "POST" do%>
    <%= text_field_tag :username %>
    <%= password_field_tag :password %>
    <%= submit_tag "Log in"%>
<%end%>

app/views/users/loginform.html.erb
<h1>Login</h1>

<%= form_tag "/users/login", method: "POST", class: 'form' do %>
  <%= label_tag :username %>
  <%= text_field_tag :username %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <% if flash[:error] %>
    <ul>
        <li class="error"><%= flash[:error] %></li>
    </ul>
  <% end %>

  <%= submit_tag "Log In" %>
<% end %>

app/views/users/new.html.erb
<div class="container" style="padding-top: 30px;">
    <h1 class="display-3" style="padding-top: 30px;">New User's Form</h1>
    <br/>
<h1> Create an account! </h1>

<div class="container" style="padding-top: 30px;">
<%= form_for @user do |f|%>
  <%= f.label :username%><br>
  <%= f.text_field :username%><br>
  
  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
     
  <%= f.submit "Sign up!" %>
<%end%>
</div>

app/views/users/show.html.erb
<div class="container">
    <h1 class="display-3" style="padding-top: 30px;"><h1 style="text-align: center; color:#00ff00
; font-size:46px;">DreemLyrics</h1>
<br/>
</div>

<div class="container">
    <h1 class="display-6">
<p> What would you like to do today, <%= logged_in_user.username %>?</p>

<br>
<%= button_to "View Available Songs", songs_path, method: :get %> </h1>

<br>

</div>

<div>
<br>
<p>
<% if logged_in? && logged_in_user.id == @user.id %>

      <%= button_to "Edit Profile", edit_user_path(@user), method: :get, class: "button" %>
      <br>
      <%= button_to "Delete Account", @user, method: :delete, class: "button" %>
    <% end %>
</p>
</div>
<br>
<div class="container" style="padding-top: 50px;">
<h2>Here's what you've memorized so far!</h2>
<% @user.memorized_lines.each do |memorized_line| %>
 <h4>Song: <%= memorized_line.lyric.song.title %></h4> <em><%= memorized_line.lyric.lines_of_lyrics %>
<br>
<% end %>

</div>